OWNER_NAME="MBUVI TECH"
PREFIX="."
PUBLIC_MODE='yes'
AUTO_READ_STATUS="yes"
AUTO_DOWNLOAD_STATUS="no"
BOT_NAME= "MBUVI-MD"
IMAGE_MENU= "https://telegra.ph/file/a7ca8d4777fa8ad977795.jpg"
NUMERO_OWNER= ""
OWNER_NAME= "᚛Mbuvi Tech᚜"
DATABASE_URL= ""
WARN_COUNT= ""
OPENAI_API_KEY= ""
STARTING_BOT_MESSAGE='yes'
ANTI_DELETE_MESSAGE='yes'

